version: "3.7"

services:
  db:
    image: postgres:11
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  client:
    container_name: seismic-risc-client
    build:
      context: ./client
    volumes:
      - ./client:/code
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      NODE_ENV:
      REACT_APP_API_KEY:
      REACT_APP_DJANGO_SITE_URL:
      REACT_APP_DJANGO_PORT:
      REACT_APP_DJANGO_API_ENDPOINT:

  api:
    container_name: seismic-risc-api
    build:
      context: ./api
      args:
        DEVBUILD: 1
    command:
      [
        "./wait_for_db.py && ./manage.py migrate --noinput && ./manage.py runserver 0.0.0.0:8000",
      ]
    volumes:
      - ./api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_CONFIGURATION:
      DATABASE_URL:

volumes:
  pgdata:
