version: 1
update_configs:
  - package_manager: "javascript"
    directory: "client/"
    update_schedule: "weekly"
    target_branch: "develop"
    default_reviewers:
      - "tudoramariei"
    default_assignees:
      - "tudoramariei"
    default_labels:
      - "dependencies"
      - "react"
